name: fact_bert
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - attrs=22.1.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - catalogue=1.0.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.4
  - cymem=2.0.6
  - cython-blis=0.7.7
  - dataclasses=0.8
  - fftw=3.3.9
  - filelock=3.9.0
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=3.0.2
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - murmurhash=1.0.7
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.6.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1s
  - packaging=22.0
  - pillow=9.3.0
  - pip=22.3.1
  - plac=1.1.0
  - preshed=3.0.6
  - protobuf=3.20.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.15
  - python_abi=3.7
  - pytorch=1.4.0
  - readline=8.1.2
  - regex=2022.7.9
  - requests=2.28.1
  - sacremoses=master
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.5.1
  - six=1.16.0
  - spacy=2.3.5
  - sqlite=3.40.1
  - srsly=1.0.5
  - thinc=7.4.5
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.9.4
  - torchvision=0.5.0
  - tqdm=4.64.1
  - transformers=4.1.1
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - wasabi=0.9.1
  - wheel=0.38.4
  - xz=5.2.6
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
