name: fact_bert
channels:
  - pytorch
  - huggingface
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=22.1.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - catalogue=1.0.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.4
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.0.90
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cudatoolkit=10.1.243
  - cymem=2.0.6
  - cython-blis=0.7.7
  - dataclasses=0.8
  - fftw=3.3.9
  - filelock=3.9.0
  - flit-core=3.6.0
  - freetype=2.11.0
  - gds-tools=1.5.0.59
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=3.0.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - murmurhash=1.0.7
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.6.3
  - nsight-compute=2022.4.0.15
  - numexpr=2.8.4
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.3.5
  - pillow=9.2.0
  - pip=22.1.2
  - plac=1.1.0
  - preshed=3.0.6
  - protobuf=3.20.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.4.0
  - pytorch-cuda=11.6
  - pytz=2022.7
  - readline=8.1.2
  - regex=2022.7.9
  - requests=2.28.1
  - sacremoses=master
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - spacy=2.3.5
  - sqlite=3.39.2
  - srsly=1.0.5
  - thinc=7.4.5
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.9.4
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - tqdm=4.64.1
  - transformers=4.0.1
  - typing=3.10.0.0
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - wasabi=0.9.1
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.11.0
  - zlib=1.2.12
  - zstd=1.5.2
