name: fact_lstm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - catalogue=2.0.8
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.0.4
  - colorama=0.4.6
  - confection=0.0.3
  - cryptography=38.0.2
  - cymem=2.0.7
  - cython-blis=0.7.8
  - dataclasses=0.8
  - fftw=3.3.9
  - flit-core=3.6.0
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - langcodes=3.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - liblapack=3.9.0
  - libuv=1.40.0
  - libzlib=1.2.13
  - llvm-openmp=12.0.1
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - murmurhash=1.0.9
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.6.3
  - numexpr=2.8.4
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1s
  - packaging=23.0
  - pandas=1.3.5
  - pathy=0.10.1
  - pip=22.3.1
  - preshed=3.0.8
  - pycparser=2.21
  - pydantic=1.9.2
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.7.15
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.9.0
  - pytz=2022.7.1
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - shellingham=1.5.0.post1
  - six=1.16.0
  - smart_open=5.2.1
  - spacy=3.4.0
  - spacy-legacy=3.0.11
  - spacy-loggers=1.0.4
  - sqlite=3.40.1
  - srsly=2.4.5
  - tbb=2021.7.0
  - thinc=8.1.5
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchtext=0.10.0
  - tqdm=4.64.1
  - typer=0.4.2
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.14
  - wasabi=0.10.1
  - wheel=0.37.1
  - xz=5.2.8
  - zipp=3.11.0
  - zlib=1.2.13
  - pip:
      - captum==0.6.0
      - cycler==0.11.0
      - fonttools==4.38.0
      - kiwisolver==1.4.4
      - matplotlib==3.5.3
      - pillow==9.4.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.6
      - pyparsing==3.0.9
