#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:0
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_bert_test_%A.out

module load 2021
module load Anaconda3/2021.05

source activate fact_bert

srun python3 bert_leakage.py --seed 42 --cap_model nic --calc_ann_leak True